{
  "formatVersion": "1.1",
  "component": {
    "url": "../../abstract-collisionless-token-map/1.0/abstract-collisionless-token-map-1.0.module",
    "group": "ru.landgrafhomyak",
    "module": "abstract-collisionless-token-map",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "abstract-collisionless-token-map-js-1.0.klib",
          "url": "abstract-collisionless-token-map-js-1.0.klib",
          "size": 20701,
          "sha512": "2f737855c5f14c481b16a99f74780008548ca6a7565a404e9bab38ad4da9ed8fd9a351ba4c6ea00899f220d40b6a19d87da487b9f712cc7f164e0253a54d05db",
          "sha256": "ccba34841425318614c8df909edb70e0ca7cbeecbbfaf7aa1c033a8f3ae2c8e7",
          "sha1": "e3304d340431c1a663a1b3a8a710afb8883e32a6",
          "md5": "5783b1f362fc26b0842696e396083b74"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "ru.landgrafhomyak.collections",
          "module": "abstract-red-black-tree",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "ru.landgrafhomyak.collections",
          "module": "abstract-red-black-priority-queue",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "abstract-collisionless-token-map-js-1.0.klib",
          "url": "abstract-collisionless-token-map-js-1.0.klib",
          "size": 20701,
          "sha512": "2f737855c5f14c481b16a99f74780008548ca6a7565a404e9bab38ad4da9ed8fd9a351ba4c6ea00899f220d40b6a19d87da487b9f712cc7f164e0253a54d05db",
          "sha256": "ccba34841425318614c8df909edb70e0ca7cbeecbbfaf7aa1c033a8f3ae2c8e7",
          "sha1": "e3304d340431c1a663a1b3a8a710afb8883e32a6",
          "md5": "5783b1f362fc26b0842696e396083b74"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "abstract-collisionless-token-map-js-1.0-sources.jar",
          "url": "abstract-collisionless-token-map-js-1.0-sources.jar",
          "size": 3822,
          "sha512": "f8da3740ea5f15aaca94f3150a73503be7f0d88c4c9d5fddc403850a3c06354fa6a3e659142733ba069b11bab43877ccef7ec0a3ae804e17949bd41756b9fab2",
          "sha256": "c229c00f574c4c8607fe8fbb252eeca877b53cc90416aa9eb5f809d72c89bb2e",
          "sha1": "5ba2f09fe551c52f6dcb975b48b8f9abf134a5f0",
          "md5": "473f2b3f5864811f166860cf492f9330"
        }
      ]
    }
  ]
}
