{
  "formatVersion": "1.1",
  "component": {
    "url": "../../abstract-collisionless-token-map/1.0/abstract-collisionless-token-map-1.0.module",
    "group": "ru.landgrafhomyak",
    "module": "abstract-collisionless-token-map",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "abstract-collisionless-token-map-jvm-1.0.jar",
          "url": "abstract-collisionless-token-map-jvm-1.0.jar",
          "size": 16302,
          "sha512": "2256fe81e2457749e226d0cd62a7b52acd98b679a0f8acdfbffa2c900e576e233f67f5bb860ae85e0e6d57b7d9a1f93eaa85895f74ec84643ee51b3ae98e06ba",
          "sha256": "121007828230a2f40b22f75cbd9d2e04d4f95822060895c499d3e2213dcd4271",
          "sha1": "d3fc76ed686ecf675019a8dcdf1322ef414ed4d8",
          "md5": "d11aecc73794603f6764974ce9bd2ac7"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "ru.landgrafhomyak.collections",
          "module": "abstract-red-black-tree",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "ru.landgrafhomyak.collections",
          "module": "abstract-red-black-priority-queue",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "abstract-collisionless-token-map-jvm-1.0.jar",
          "url": "abstract-collisionless-token-map-jvm-1.0.jar",
          "size": 16302,
          "sha512": "2256fe81e2457749e226d0cd62a7b52acd98b679a0f8acdfbffa2c900e576e233f67f5bb860ae85e0e6d57b7d9a1f93eaa85895f74ec84643ee51b3ae98e06ba",
          "sha256": "121007828230a2f40b22f75cbd9d2e04d4f95822060895c499d3e2213dcd4271",
          "sha1": "d3fc76ed686ecf675019a8dcdf1322ef414ed4d8",
          "md5": "d11aecc73794603f6764974ce9bd2ac7"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "abstract-collisionless-token-map-jvm-1.0-sources.jar",
          "url": "abstract-collisionless-token-map-jvm-1.0-sources.jar",
          "size": 3822,
          "sha512": "f8da3740ea5f15aaca94f3150a73503be7f0d88c4c9d5fddc403850a3c06354fa6a3e659142733ba069b11bab43877ccef7ec0a3ae804e17949bd41756b9fab2",
          "sha256": "c229c00f574c4c8607fe8fbb252eeca877b53cc90416aa9eb5f809d72c89bb2e",
          "sha1": "5ba2f09fe551c52f6dcb975b48b8f9abf134a5f0",
          "md5": "473f2b3f5864811f166860cf492f9330"
        }
      ]
    }
  ]
}
