{
  "formatVersion": "1.1",
  "component": {
    "url": "../../abstract-collisionless-token-map/1.0/abstract-collisionless-token-map-1.0.module",
    "group": "ru.landgrafhomyak",
    "module": "abstract-collisionless-token-map",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "ru.landgrafhomyak.collections",
          "module": "abstract-red-black-tree",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "ru.landgrafhomyak.collections",
          "module": "abstract-red-black-priority-queue",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "abstract-collisionless-token-map.klib",
          "url": "abstract-collisionless-token-map-linuxx64-1.0.klib",
          "size": 21582,
          "sha512": "ce4de23d44c0c0dded1c200e1d3f8fd0684e8fbca7a631b67342b8eb650a2d5342a5e1ea8ed60fcfbe4595fc30ca3fc940cbbca862cf5d202e630413a3cf72cd",
          "sha256": "858f1a31a0af3221e202c26ddd0b122b49c92d9b9436169dfa0aa3b32dfecd77",
          "sha1": "ed76e08177f3ab998ecb68dc73fc1b16b18b957b",
          "md5": "7a3e10d1f37116f6d29f5c95ecffbc48"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "abstract-collisionless-token-map-linuxx64-1.0-sources.jar",
          "url": "abstract-collisionless-token-map-linuxx64-1.0-sources.jar",
          "size": 3822,
          "sha512": "f8da3740ea5f15aaca94f3150a73503be7f0d88c4c9d5fddc403850a3c06354fa6a3e659142733ba069b11bab43877ccef7ec0a3ae804e17949bd41756b9fab2",
          "sha256": "c229c00f574c4c8607fe8fbb252eeca877b53cc90416aa9eb5f809d72c89bb2e",
          "sha1": "5ba2f09fe551c52f6dcb975b48b8f9abf134a5f0",
          "md5": "473f2b3f5864811f166860cf492f9330"
        }
      ]
    }
  ]
}
