{
  "formatVersion": "1.1",
  "component": {
    "url": "../../abstract-collisionless-token-map/1.0/abstract-collisionless-token-map-1.0.module",
    "group": "ru.landgrafhomyak",
    "module": "abstract-collisionless-token-map",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "ru.landgrafhomyak.collections",
          "module": "abstract-red-black-tree",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "ru.landgrafhomyak.collections",
          "module": "abstract-red-black-priority-queue",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "abstract-collisionless-token-map.klib",
          "url": "abstract-collisionless-token-map-tvosx64-1.0.klib",
          "size": 21573,
          "sha512": "5867e0331305a1102824702c5ae67e2116eb7cddee058be218ce1787536ee00d67a7c9248f2b2bff6680d59c59ce90d7dea9621045755a5b37b52a9daa348c50",
          "sha256": "bd17a3b3c1dee150076c3ba06956c66933153338145f2bd39161ea97959f9d73",
          "sha1": "187646c2013275a561262aab16aee34e6c0f775c",
          "md5": "e8fb740426eb4dad32ab14b8277fab1c"
        }
      ]
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "abstract-collisionless-token-map-tvosx64-1.0-sources.jar",
          "url": "abstract-collisionless-token-map-tvosx64-1.0-sources.jar",
          "size": 3822,
          "sha512": "f8da3740ea5f15aaca94f3150a73503be7f0d88c4c9d5fddc403850a3c06354fa6a3e659142733ba069b11bab43877ccef7ec0a3ae804e17949bd41756b9fab2",
          "sha256": "c229c00f574c4c8607fe8fbb252eeca877b53cc90416aa9eb5f809d72c89bb2e",
          "sha1": "5ba2f09fe551c52f6dcb975b48b8f9abf134a5f0",
          "md5": "473f2b3f5864811f166860cf492f9330"
        }
      ]
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "ru.landgrafhomyak.collections",
          "module": "abstract-red-black-tree",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "ru.landgrafhomyak.collections",
          "module": "abstract-red-black-priority-queue",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "abstract-collisionless-token-map-tvosx64-1.0-metadata.jar",
          "url": "abstract-collisionless-token-map-tvosx64-1.0-metadata.jar",
          "size": 261,
          "sha512": "b596237b0175a636a6fda8397a7491e78649ed86b1d1b65ffb298704dd6965672e0130c5c9e5d59eeafaa2caea73d27070508c287b17703a9ecd073d238c0540",
          "sha256": "eed25ed0e301e743707caeebead6912363ea5c21195fb34967e7d7b2cf8c14c9",
          "sha1": "fc63e0c51208387e7212e7ac9e543936b18c2218",
          "md5": "4b46b282d79a7b41800879b74ad39b1a"
        }
      ]
    }
  ]
}
